name: codespell
on: [push, pull_request]
permissions: {}
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
