            - name: Codespell with annotations
  # You may pin to the exact commit or the version.
  # uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
  uses: codespell-project/actions-codespell@v2.0
  with:
    # If set, check file names as well
    check_filenames: true
          
